spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 146666397011-6vcrmg7b760acgd3jt76f9il2dbbt0f2.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile